In [1]:
import numpy as np

In [2]:
#mat = np.array([[1,2,3],[2,3,4],[1,1,1],[4,5,4],[2,2,6]])

In [47]:
mat = np.random.randint(0,99,size=(200,3))

In [48]:
mat

array([[15, 19, 28],
       [22, 55, 94],
       [25, 54, 43],
       [50, 56, 55],
       [43, 41,  8],
       [ 6, 88, 96],
       [35, 57, 92],
       [47, 15, 50],
       [70, 10, 39],
       [96, 63, 89],
       [ 4, 21, 59],
       [90, 18, 71],
       [83,  1,  3],
       [ 5,  9,  1],
       [ 8, 83, 79],
       [90, 72, 15],
       [87, 45,  1],
       [67, 45, 79],
       [71, 67, 60],
       [97, 64, 82],
       [11, 91, 34],
       [36, 28, 65],
       [37, 61, 97],
       [ 8, 81, 46],
       [77, 24, 26],
       [84, 67, 41],
       [ 9, 71, 37],
       [25, 48, 16],
       [38, 23, 98],
       [37, 74, 32],
       [74, 38, 27],
       [39, 86, 55],
       [96, 61, 39],
       [19, 85, 67],
       [50, 52, 41],
       [69, 80, 39],
       [70, 81, 85],
       [64, 70, 95],
       [72, 85, 77],
       [86, 94, 69],
       [42, 70, 41],
       [40,  6,  8],
       [29, 17, 39],
       [ 5, 62, 47],
       [71,  3, 64],
       [70, 60, 83],
       [97, 89, 49],
       [45, 5

In [49]:
def initialize_centroids(data, k):
    
    n = data.shape[0] # number of data points
    # Randomly choose index of the data
    rand_indices = np.random.randint(0, n, k)
    centroids = data[rand_indices,:]
    
    return centroids

In [78]:
init_c = initialize_centroids(mat, 3)

In [79]:
init_c

array([[8, 4, 4],
       [3, 4, 8],
       [0, 6, 5]])

In [107]:
init_c.shape

(3, 3)

In [51]:
from sklearn.metrics.pairwise import pairwise_distances
dist = pairwise_distances(mat, mat, metric='euclidean')

In [82]:
pairwise_distances(mat, init_c, metric='euclidean').shape

(200, 3)

In [84]:
init_c

array([[8, 4, 4],
       [3, 4, 8],
       [0, 6, 5]])

In [85]:
mat

array([[8, 5, 2],
       [1, 2, 7],
       [0, 5, 7],
       [8, 0, 1],
       [6, 7, 5],
       [8, 4, 4],
       [0, 5, 6],
       [0, 1, 7],
       [4, 2, 4],
       [0, 6, 2],
       [8, 6, 3],
       [0, 5, 8],
       [7, 1, 7],
       [0, 0, 8],
       [8, 1, 2],
       [6, 7, 4],
       [5, 4, 5],
       [7, 7, 4],
       [8, 8, 7],
       [1, 3, 3],
       [4, 1, 6],
       [4, 0, 6],
       [7, 3, 3],
       [7, 6, 8],
       [7, 8, 2],
       [1, 6, 0],
       [3, 4, 8],
       [4, 3, 8],
       [6, 1, 0],
       [2, 0, 0],
       [5, 7, 2],
       [2, 4, 4],
       [7, 7, 0],
       [8, 0, 2],
       [4, 2, 0],
       [7, 5, 8],
       [0, 5, 2],
       [7, 0, 0],
       [2, 0, 5],
       [8, 2, 1],
       [3, 3, 6],
       [7, 1, 8],
       [8, 5, 2],
       [8, 1, 6],
       [5, 5, 8],
       [7, 1, 4],
       [6, 6, 4],
       [3, 5, 7],
       [7, 0, 8],
       [6, 1, 6],
       [3, 8, 1],
       [1, 6, 4],
       [7, 4, 8],
       [0, 6, 8],
       [1, 0, 8],
       [2,

In [114]:
def euclidean(q, data):
    euc = np.zeros((data.shape[1],data.shape[0]))
    for i in range(data.shape[1]):
        euc[i] = np.sqrt(np.sum(((q[i]-mat)**2), axis=1))
    return euc.transpose()

In [115]:
dist = euclidean(init_c, mat)

In [116]:
dist.shape

(200, 3)

In [117]:
dist

array([[  2.23606798,   7.87400787,   8.60232527],
       [  7.87400787,   3.        ,   4.58257569],
       [  8.60232527,   3.31662479,   2.23606798],
       [  5.        ,   9.48683298,  10.77032961],
       [  3.74165739,   5.19615242,   6.08276253],
       [  0.        ,   6.40312424,   8.30662386],
       [  8.30662386,   3.74165739,   1.41421356],
       [  9.05538514,   4.35889894,   5.38516481],
       [  4.47213595,   4.58257569,   5.74456265],
       [  8.48528137,   7.        ,   3.        ],
       [  2.23606798,   7.34846923,   8.24621125],
       [  9.        ,   3.16227766,   3.16227766],
       [  4.35889894,   5.09901951,   8.83176087],
       [  9.79795897,   5.        ,   6.70820393],
       [  3.60555128,   8.36660027,   9.89949494],
       [  3.60555128,   5.83095189,   6.164414  ],
       [  3.16227766,   3.60555128,   5.38516481],
       [  3.16227766,   6.40312424,   7.14142843],
       [  5.        ,   6.4807407 ,   8.48528137],
       [  7.14142843,   5.47722

In [118]:
pairwise_distances(mat, init_c, metric='euclidean')

array([[  2.23606798,   7.87400787,   8.60232527],
       [  7.87400787,   3.        ,   4.58257569],
       [  8.60232527,   3.31662479,   2.23606798],
       [  5.        ,   9.48683298,  10.77032961],
       [  3.74165739,   5.19615242,   6.08276253],
       [  0.        ,   6.40312424,   8.30662386],
       [  8.30662386,   3.74165739,   1.41421356],
       [  9.05538514,   4.35889894,   5.38516481],
       [  4.47213595,   4.58257569,   5.74456265],
       [  8.48528137,   7.        ,   3.        ],
       [  2.23606798,   7.34846923,   8.24621125],
       [  9.        ,   3.16227766,   3.16227766],
       [  4.35889894,   5.09901951,   8.83176087],
       [  9.79795897,   5.        ,   6.70820393],
       [  3.60555128,   8.36660027,   9.89949494],
       [  3.60555128,   5.83095189,   6.164414  ],
       [  3.16227766,   3.60555128,   5.38516481],
       [  3.16227766,   6.40312424,   7.14142843],
       [  5.        ,   6.4807407 ,   8.48528137],
       [  7.14142843,   5.47722

In [113]:
dist.transpose().shape

(200, 3)

In [100]:
np.zeros((10,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [101]:
np.zeros((10,3)).reshape((3,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [91]:
euc.shape

(200,)

In [52]:
dist

array([[  0.        ,  75.50496672,  39.37003937, ...,  25.61249695,
         73.5187051 ,  23.02172887],
       [ 75.50496672,   0.        ,  51.09794516, ...,  85.02352616,
         35.86084215,  87.18371408],
       [ 39.37003937,  51.09794516,   0.        , ...,  54.09251335,
         55.36244214,  53.94441584],
       ..., 
       [ 25.61249695,  85.02352616,  54.09251335, ...,   0.        ,
         71.7565328 ,   5.09901951],
       [ 73.5187051 ,  35.86084215,  55.36244214, ...,  71.7565328 ,
          0.        ,  75.45197148],
       [ 23.02172887,  87.18371408,  53.94441584, ...,   5.09901951,
         75.45197148,   0.        ]])

In [53]:
dist.shape

(200, 200)

In [54]:
def euclidean(q, data):
    euc = np.sqrt(np.sum((q-data)**2, axis=1))
    return euc

In [55]:
euclidean(mat[0], mat)

array([   0.        ,   75.50496672,   39.37003937,   57.64546817,
         40.84115571,   97.29337079,   77.07139547,   39.03844259,
         56.80668975,  110.53506231,   32.95451411,   86.45808233,
         74.65252842,   30.47950131,   82.13403679,   92.75235846,
         81.17265549,   77.3369252 ,   80.39900497,  108.00462953,
         72.36021006,   43.48562981,   83.71977066,   64.93843238,
         62.23343153,   85.0529247 ,   53.1130869 ,   32.93933818,
         73.79024326,   59.37171044,   61.99193496,   76.11832894,
         91.90212185,   76.76587784,   49.82971001,   82.20705566,
        100.58826969,   97.42176348,  100.0299955 ,  111.1170554 ,
         59.15234568,   34.55430509,   17.91647287,   48.06245936,
         68.46897107,   87.92610534,  109.84079388,   43.8634244 ,
         40.60788101,   88.26097665,   91.80413934,   23.9582971 ,
         55.06359959,   58.52349955,   74.90660852,   73.50510186,
         44.15880433,   36.40054945,   71.59608928,   49.50757

In [56]:
pairwise_distances(mat, mat[0])

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[   0.        ],
       [  75.50496672],
       [  39.37003937],
       [  57.64546817],
       [  40.84115571],
       [  97.29337079],
       [  77.07139547],
       [  39.03844259],
       [  56.80668975],
       [ 110.53506231],
       [  32.95451411],
       [  86.45808233],
       [  74.65252842],
       [  30.47950131],
       [  82.13403679],
       [  92.75235846],
       [  81.17265549],
       [  77.3369252 ],
       [  80.39900497],
       [ 108.00462953],
       [  72.36021006],
       [  43.48562981],
       [  83.71977066],
       [  64.93843238],
       [  62.23343153],
       [  85.0529247 ],
       [  53.1130869 ],
       [  32.93933818],
       [  73.79024326],
       [  59.37171044],
       [  61.99193496],
       [  76.11832894],
       [  91.90212185],
       [  76.76587784],
       [  49.82971001],
       [  82.20705566],
       [ 100.58826969],
       [  97.42176348],
       [ 100.0299955 ],
       [ 111.1170554 ],
       [  59.15234568],
       [  34.554

In [57]:
def assign_clusters(data, centroids):
    
    distances_from_centroids = pairwise_distances(data, centroids, metric='euclidean')
    cluster_assignment = np.argmin(distances_from_centroids, axis=1)
    
    return cluster_assignment

In [58]:
cent = initialize_centroids(mat, 3)

In [59]:
clusters = assign_clusters(mat, cent)

In [61]:
mat[clusters==0].shape

(60, 3)

In [62]:
mat[clusters==1].shape

(82, 3)

In [63]:
mat[clusters==2].shape

(58, 3)

In [64]:
def revise_centroids(data, k, cluster_assignment):
    new_centroids = []
    for i in range(k):
        # Select all data points that belong to cluster i. Fill in the blank (RHS only)
        member_data_points = data[cluster_assignment==i]
        # Compute the mean of the data points. Fill in the blank (RHS only)
        centroid = member_data_points.mean(axis=0)
        
        # Convert numpy.matrix type to numpy.ndarray type
        #centroid = centroid.A1
        new_centroids.append(centroid)
    new_centroids = np.array(new_centroids)
    
    return new_centroids

In [77]:
mat[clusters==0].mean(axis=0)

array([ 6.39705882,  2.38235294,  4.26470588])

In [65]:
new_cent = revise_centroids(mat, 3, clusters)

In [66]:
new_cent

array([[ 24.66666667,  68.11666667,  61.23333333],
       [ 45.04878049,  25.31707317,  35.98780488],
       [ 78.03448276,  62.96551724,  66.25862069]])

In [67]:
assign_clusters(mat, new_cent)

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 2, 2, 0, 1, 0,
       0, 1, 2, 0, 1, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 0, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 2, 2, 1, 1, 0, 1, 2,
       0, 1, 1, 2, 0, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1, 0, 0, 2, 2, 1,
       0, 2, 1, 1, 1, 1, 2, 1, 2, 0, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 2, 2, 2, 0, 0, 2, 1, 2,
       2, 0, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1])

In [70]:
def kmeans(data, k, initial_centroids, maxiter=300):

    centroids = initial_centroids[:]
    prev_cluster_assignment = None
    
    for itr in range(maxiter):        
        # 1. Make cluster assignments using nearest centroids
        cluster_assignment = assign_clusters(data, centroids)
            
        # 2. Compute a new centroid for each of the k clusters, averaging all data points assigned to that cluster.
        centroids = revise_centroids(data, k, cluster_assignment)
            
        # Check for convergence: if none of the assignments changed, stop
        if prev_cluster_assignment is not None and \
          (prev_cluster_assignment==cluster_assignment).all():
            break
        
        # Print number of new assignments 
        if prev_cluster_assignment is not None:
            num_changed = np.sum(prev_cluster_assignment!=cluster_assignment)
            
            print('    {0:5d} elements changed their cluster assignment.'.format(num_changed))   
        
        # Record heterogeneity convergence metric
        #if record_heterogeneity is not None:
            # YOUR CODE HERE
        #    score = compute_heterogeneity(data, k, centroids, cluster_assignment)
        #    record_heterogeneity.append(score)
        
        prev_cluster_assignment = cluster_assignment[:]
        
    return centroids, cluster_assignment

In [74]:
mat = np.random.randint(0,9,size=(200,3))

In [75]:
init_cent = initialize_centroids(mat, 3)
p_centroids, clusters = kmeans(mat, 3, init_cent)

       11 elements changed their cluster assignment.
        6 elements changed their cluster assignment.
        1 elements changed their cluster assignment.


In [76]:
p_centroids

array([[ 6.39705882,  2.38235294,  4.26470588],
       [ 1.51851852,  1.88888889,  3.33333333],
       [ 3.56410256,  6.46153846,  4.24358974]])